// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjqjtvbodinnniyzjujc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcWp0dmJvZGlubm5peXpqdWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTI3ODAsImV4cCI6MjA2MzQyODc4MH0.o65gPzqXKb3yp_fKjo56_WcTaQReyzwpJjxBhAxvuTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);